### ISSUE TITLE
Roadmap to release v0.1

### ISSUE THREAD

**Issue by uvchik** [oemof/oemof#216]
@oemof/oemof I think it is time for the release. Please help.
- Check the issues assigned to you with milestone v0.1.0 until the end of October.
- Proofread the documentation on the `release/v0.1' branch and let us know which parts have been read already (-> [oemof documentation](http://oemof.readthedocs.io/en/release-v0.1/)).
- Report urgent bugs of v0.1beta.
- @oemof/oemof-core What about the structure of the network module?
- Have a look at [the thoughts we had in May](https://github.com/oemof/oemof/wiki/Release-Roadmap).

**Comment by simnh** [comment]
@uvchik:  thanks a lot for the documentation! I will read it this week. I think it's sufficient for version 0.1

**Comment by uvchik** [comment]
Add the web-meeting (#207) we decided to release on the November 1.

ToDos:
 * proofread the documentation (@ckaldemeyer, @gplssm, @simnh) 
 * describe grouping function (@simnh) 
 * revise "idea of a framework" especially the figure :exclamation: 
 * close or postpone issues assigned to you ( @ckaldemeyer, @gnn, @caro-rli, @simnh, @uvchik)

**Comment by uvchik** [comment]
@birgits created two new branches `deprecated/dev` and `deprecated/master`. These branches can be used for bug fixes and little changes to the pre-v0.1 oemof cosmos. On these branches releases as v0.0.9, v0.0.10 etc. are possible.

Therefore I would like to set the `master` and the `dev` branches to the actual state on November 1.

If you (@oemof/oemof) have a problem with this procedure, please add a comment here.

**Comment by uvchik** [comment]
Could you all please have a look to the whatsnew file for version 0.1. I think we could add some lines but somebody has to write a few lines of what the new version is about.

@oemof/oemof Who would do it?

**Comment by uvchik** [comment]
As we are quite proud of our new version I think we should use to start a little more public relations. I think we should write a small text to be published at wordpress, openmod,....

Where else should we announce the new release?
What about the openmod meeting?
Who could write a little text?

**Comment by simnh** [comment]
I can write it once we finished this one. Maybe strommarkt gruppe? I think we could also try to add 
it to the openscience framework properly?

**Comment by gplssm** [comment]
I hope you find finally some energy to talk about what achieved @simnh and @uvchik and others! Just a side-note here, @ludee reported from Milano that people where asking about oemof and further development.
In order to keep an overview on post-release communication channels, I create a checklist for release announcements (feel free to extend and change responsibilities)

- [ ] oemof.wordpress.com (should be a medium-long more explanatory post) @uvchik @simnh 
- [ ] openmod mailing list @simnh 
- [ ] strommarktgruppen mailing list @simnh 
- [ ] news on [RLI page](http://reiner-lemoine-institut.de/) @gplssm @uvchik 
- [ ] mail to personal mail addresses of potential interested people @gplssm
 - people that talked to @ludee in milano
 - HTW research group
 - ...

**Comment by simnh** [comment]
Ok, I will probably not be able to write the notes and sent it today, but I can do it on the train tomorrow and hopefully (if I get internet) send it tomorrow evening.

**Comment by uvchik** [comment]
It's done.

https://oemof.wordpress.com/news/
http://oemof.readthedocs.io/en/stable/

**Comment by simnh** [comment]
Thanks a lot @uvchik !!!!! Looks great

**Comment by ckaldemeyer** [comment]
Thanks a lot to both of you @uvchik, @simnh . I think this is a real milestone!

**Comment by ckaldemeyer** [comment]
I just discovered in the link to the examples in the pypi documentation (https://pypi.python.org/pypi/oemof/0.1.0) isn't working. 

Was it just downloading the old documentation, fixing and re-uploading? I would then fix it quickly..

**Comment by uvchik** [comment]
@ckaldemeyer ; Thank you. Fixed!
