### ISSUE TITLE
Roadmap to 0.2.0

### ISSUE THREAD

**Issue by uvchik** [oemof/oemof#327]
There are some changes in the pipe that may change the API.

What about heading v0.2.0 (when?) and collect all API changes. Is it possible to release 0.1.5 with a bunch of FutureWarnings?

 * [x] Replacing all transformer class by one Transformer (see #351)

* [x] Changing the results API: see #329

* [x] Adding periods (Breaks the API only if you use additional constraints)

* [x] Adding custom components

* [x] Doing some polishing: see. #330 and #328

* [x] Removing hidden magic e.g. making automatic instatiation like `Source(....)` without a reference impossible or at least hide the possibility within the examples

* [x] Use `__init__.py`s consistently

* [x] Move everything except sink, source, transformer and bus to custom components

* [x] Remove redundancies of EnergySystem and OperationModel

* [x] Introduce Basic Model for Multi-Period introduction 

* [x] Move some classes to EnergySystem (according to: #315)

* [x] Removing the csv-reader (see #355)!

* [x] How to import consistently e.g. `import oemof.solph` with `solph.my_component()` or `from oemof.solph import (comps)` with `my_component` ?

* [x] Integrating a license in all files. See: #262 and https://github.com/oemof/organisation/issues/9

* [x] Add API examples to all solph components e.g. https://github.com/oemof/oemof/blob/dev/oemof/solph/components.py consistently (like for network classes) @ckaldemeyer

**Comment by simnh** [comment]
I guess we can aim for it at the end of summer. I would like to release it when the paper is released (5th october). @gnn will hopefully have time to add some of the ideas from the last developer meeting.

**Comment by uvchik** [comment]
Let's say autumn 😏 

Just add your topics in the first comment or would you rather like to open a wiki?

**Comment by ckaldemeyer** [comment]
> Let's say autumn

:+1: 

> Just add your topics in the first comment or would you rather like to open a wiki?

I think the TODO list is enough.

**Comment by ckaldemeyer** [comment]
I have added and linked some todos and issues

**Comment by ckaldemeyer** [comment]
I have added a TODO. @uvchik has proposed to jump directly to V.0.2 for the next release and I would agree.

**Comment by ckaldemeyer** [comment]
https://github.com/oemof/oemof/pull/329

**Comment by ckaldemeyer** [comment]
https://github.com/oemof/oemof/issues/328

**Comment by ckaldemeyer** [comment]
https://github.com/oemof/oemof/issues/335

**Comment by uvchik** [comment]
I added a new `v0.2.0` milestone and removed the `0.1.x` milestones as we decided that there will not be a release before `v0.2.0`. If you think that you will not be able to finish you work until the next release you can set it to `0.2.1`. Feel free to add later milestones.

**Comment by ckaldemeyer** [comment]
> I added a new v0.2.0 milestone and removed the 0.1.x milestones as we decided that there will not be a release before v0.2.0. If you think that you will not be able to finish you work until the next release you can set it to 0.2.1. Feel free to add later milestones for long time projects.

Thanks. I am planning to be finished by the end of October.

**Comment by uvchik** [comment]
I set the release to the latest possible date, if we want to release this year but we could choose an earlier date.

**Comment by simnh** [comment]
I added some points, that I like to add until the end of month...

**Comment by uvchik** [comment]
After talking to @ckaldemeyer I added:

```
Who will be able to maintain the csv-reader in the future?
```

**Comment by ckaldemeyer** [comment]
I have added:

> How to import consistently e.g. import oemof.solph with solph.my_component() or from oemof.solph import (comps) with my_component ?

**Comment by ckaldemeyer** [comment]
I have added the TODO of integrating a license in every file: https://github.com/oemof/organisation/issues/9

**Comment by uvchik** [comment]
> I have added the TODO of integrating a license in every file: oemof/organisation#9

This also related to #262. I added it above.

**Comment by uvchik** [comment]
I moved obvious stuff to the last todo list #382. 

@simnh , @ckaldemeyer : Please make suggestions how to handle your last open topics.
